### PR TITLE
fix relative paths for building test pages in Travis

### PR DESCRIPTION
**Pull request by priley86**
* this makes script paths relative so that test pages can be viewed in Travis in a developer's fork once enabled for Travis builds.

Story: [PTNFLY-2274](https://patternfly.atlassian.net/browse/PTNFLY-2274)

### CODE REVIEW

**Comment by priley86** [comment]
rawgit pages can be viewed [here](https://rawgit.com/priley86/patternfly-webcomponents/relative-paths-dist/index.html) in my fork's `-dist` branch after enabling Travis to build via `AUTH_TOKEN`. 

@bleathem @dlabrecq is this an OK process for enabling PR reviews/tests pages? I believe @bleathem mentioned something about a deploy token, but am not sure if this is required for building with Travis in our fork. 

anything else for this PR needed? I can put a link to these test pages on the README, along with a markdown doc on how to setup `AUTH_TOKEN` build if we want that.

**Comment by dlabrecq** [comment]
Brian's gh-pages script uses an encrypted deploy key, which is stored in the repo itself -- see APF. We could modify Travis to also use this approach, but I'm not certain how that would work with forked repos? That is, considering Travis must also push to the master-dist branch of your forked repo -- I believe only the patternfly-build user has the key?

The AUTH_TOKEN is easy enough to set up, tho.

**Comment by priley86** [comment]
yep, +1 for referencing that link in the README.

@bleathem if we are OK with encouraging the use of `AUTH_TOKEN` in our forks/Travis, I will setup a quick "how to" .md on how to do this for any newbies. =)

**Comment by priley86** [comment]
reminder to self : update paths of recently merged `pf-dropdown` before merge.

**Comment by priley86** [comment]
rebased with latest and added note to README w/ test pages link.

**Comment by bleathem** [comment]
:+1:  I'm ok with merging this.  Future changes can be addressed in an additional PR.

**Pull request merged**
